In [35]:
# EDA
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

sns.set_style('whitegrid')

# Machine Learning
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

### Carregar os dados


In [36]:
# Carregar os dados
df_leads = pd.read_csv('./datasets/leads_cleaned.csv')

In [37]:
# Mostrar as primeiras linhas
df_leads.head(10)

Lead Origin     Lead Source  Do Not Email  Do Not Call  \
0                      API      Olark Chat             0            0   
1                      API  Organic Search             0            0   
2  Landing Page Submission  Direct Traffic             0            0   
3  Landing Page Submission  Direct Traffic             0            0   
4  Landing Page Submission          Google             0            0   
5                      API      Olark Chat             0            0   
6  Landing Page Submission          Google             0            0   
7                      API      Olark Chat             0            0   
8  Landing Page Submission  Direct Traffic             0            0   
9                      API          Google             0            0   

   Converted  TotalVisits  Total Time Spent on Website  Page Views Per Visit  \
0          0          0.0                            0                   0.0   
1          0          5.0                          674                   2.5   
2          1          2.0                         1532                   2.0   
3          0          1.0                          305                   1.0   
4          1          2.0                         1428                   1.0   
5          0          0.0                            0                   0.0   
6          1          2.0                         1640                   2.0   
7          0          0.0                            0                   0.0   
8          0          2.0                           71                   2.0   
9          0          4.0                           58                   4.0   

             Last Activity  Search  Newspaper Article  X Education Forums  \
0  Page Visited on Website       0                  0                   0   
1             Email Opened       0                  0                   0   
2             Email Opened       0                  0                   0   
3              Unreachable       0                  0                   0   
4        Converted to Lead       0                  0                   0   
5  Olark Chat Conversation       0                  0                   0   
6             Email Opened       0                  0                   0   
7  Olark Chat Conversation       0                  0                   0   
8             Email Opened       0                  0                   0   
9             Email Opened       0                  0                   0   

   Newspaper  Digital Advertisement  Through Recommendations  \
0          0                      0                        0   
1          0                      0                        0   
2          0                      0                        0   
3          0                      0                        0   
4          0                      0                        0   
5          0                      0                        0   
6          0                      0                        0   
7          0                      0                        0   
8          0                      0                        0   
9          0                      0                        0   

   A free copy of Mastering The Interview Last Notable Activity  
0                                       0              Modified  
1                                       0          Email Opened  
2                                       1          Email Opened  
3                                       0              Modified  
4                                       0              Modified  
5                                       0              Modified  
6                                       0              Modified  
7                                       0              Modified  
8                                       1          Email Opened  
9                                       0          Email Opened

In [38]:
# Mostrar as últimas linhas
df_leads.tail(10)

Lead Origin     Lead Source  Do Not Email  Do Not Call  \
9064  Landing Page Submission          Google             0            0   
9065  Landing Page Submission          Google             0            0   
9066  Landing Page Submission  Direct Traffic             0            0   
9067                      API  Direct Traffic             0            0   
9068  Landing Page Submission  Direct Traffic             0            0   
9069  Landing Page Submission  Direct Traffic             1            0   
9070  Landing Page Submission  Direct Traffic             0            0   
9071  Landing Page Submission  Direct Traffic             1            0   
9072  Landing Page Submission          Google             0            0   
9073  Landing Page Submission  Direct Traffic             0            0   

      Converted  TotalVisits  Total Time Spent on Website  \
9064          0          2.0                          870   
9065          1          8.0                         1016   
9066          0          2.0                         1770   
9067          1         13.0                         1409   
9068          1          5.0                          210   
9069          1          8.0                         1845   
9070          0          2.0                          238   
9071          0          2.0                          199   
9072          1          3.0                          499   
9073          1          6.0                         1279   

      Page Views Per Visit      Last Activity  Search  Newspaper Article  \
9064                  2.00       Email Opened       0                  0   
9065                  4.00       Email Opened       0                  0   
9066                  2.00           SMS Sent       0                  0   
9067                  2.60           SMS Sent       0                  0   
9068                  2.50           SMS Sent       0                  0   
9069                  2.67  Email Marked Spam       0                  0   
9070                  2.00           SMS Sent       0                  0   
9071                  2.00           SMS Sent       0                  0   
9072                  3.00           SMS Sent       0                  0   
9073                  3.00           SMS Sent       0                  0   

      X Education Forums  Newspaper  Digital Advertisement  \
9064                   0          0                      0   
9065                   0          0                      0   
9066                   0          0                      0   
9067                   0          0                      0   
9068                   0          0                      0   
9069                   0          0                      0   
9070                   0          0                      0   
9071                   0          0                      0   
9072                   0          0                      0   
9073                   0          0                      0   

      Through Recommendations  A free copy of Mastering The Interview  \
9064                        0                                       0   
9065                        0                                       0   
9066                        0                                       1   
9067                        0                                       0   
9068                        0                                       0   
9069                        0                                       0   
9070                        0                                       1   
9071                        0                                       1   
9072                        0                                       0   
9073                        0                                       1   

     Last Notable Activity  
9064          Email Opened  
9065          Email Opened  
9066              SMS Sent  
9067              SMS Sent  
9068              Modified  
9069     Em

In [39]:
# Mostrar estrutura do datset
df_leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9074 entries, 0 to 9073
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype  
---  ------                                  --------------  -----  
 0   Lead Origin                             9074 non-null   object 
 1   Lead Source                             9074 non-null   object 
 2   Do Not Email                            9074 non-null   int64  
 3   Do Not Call                             9074 non-null   int64  
 4   Converted                               9074 non-null   int64  
 5   TotalVisits                             9074 non-null   float64
 6   Total Time Spent on Website             9074 non-null   int64  
 7   Page Views Per Visit                    9074 non-null   float64
 8   Last Activity                           9074 non-null   object 
 9   Search                                  9074 non-null   int64  
 10  Newspaper Article                       9074 non-null   int6

### Preparação dos dados

In [40]:
# Preparar os dados para o modelo
X = df_leads.drop(columns=['Converted'])
y = df_leads['Converted']

In [41]:
# Criar uma lista de colunas para a parte de interpretabilidade
numeric_features = X.select_dtypes(include=['number']).columns
categorical_features = X.select_dtypes(include=['object']).columns

In [42]:
# Usar o preprocessor já salvo anteriormente
import joblib
preprocessor = joblib.load('./preprocessor_dataset_leads.pkl')

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=51)

In [44]:
# Aplicar preprocessor
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [45]:
# Mostrar a estrutura de treino e teste
print(X_train.shape)
print(X_test.shape)

(7259, 68)
(1815, 68)


### Treinamento do Modelo

In [213]:
# Criar o modelo de BoostingClassifier
boosting_model = AdaBoostClassifier(
  estimator=LogisticRegression(),
  n_estimators=50,
  learning_rate=0.7,
  random_state=51
)

In [214]:
# Treinar o modelo
boosting_model.fit(X_train, y_train)

AdaBoostClassifier(estimator=LogisticRegression(), learning_rate=0.7,
                   random_state=51)

### Avaliação do Modelo

In [215]:
# Fazer predições no conjunto de testes
y_pred = boosting_model.predict(X_test)

In [216]:
# Métricas do modelo
accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [217]:
# Mostrar métricas
print(f'Acurácia: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1-Score: {f1}')

Acurácia: 0.7851239669421488
Precision: 0.7473498233215548
Recall: 0.6313432835820896
F1-Score: 0.6844660194174758


In [218]:
# Mostrar a matriz de confusão
conf_matriz = confusion_matrix(y_test, y_pred)

fig = px.imshow(conf_matriz,
                labels=dict(x='Predição', y='Real', color="Contagem"),
                x=['Not Converted', 'Converted'],
                y=['Not Converted', 'Converted'],
                color_continuous_scale='Viridis')

fig.update_traces(text=conf_matriz, texttemplate="%{z}")
fig.update_layout(coloraxis_showscale=False)
fig.show()

In [219]:
# Calcular a importância das variáveis
importances = np.mean([np.abs(estimator.coef_[0]) for estimator in boosting_model.estimators_],axis=0)

In [220]:
# Obter os nomes reais das features
feature_names = (numeric_features.tolist() + preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features).tolist())

In [221]:
# Criar um Dataframe combinando os nomes das variáveis com as importâncias (coeficientes)
df_feature_importances = pd.DataFrame({"Feature": feature_names, "Importance":importances })

In [222]:
# Ordenar Dataframe pela importância
df_feature_importances = df_feature_importances.sort_values(by='Importance', ascending=True)

In [223]:
# Plotar o gráfico de importância
fig = px.bar(df_feature_importances, x='Importance', y='Feature', orientation='h', title='Importância das Features (Baseada nos coeficientes absolutos)')

fig.update_layout(height=1280, width=1000, yaxis={"categoryorder": 'total ascending'})
fig.show()

### Saídas do Modelo

In [224]:
# Erros nos estimadores
boosting_model.estimator_errors_

array([0.37994214, 0.31869664, 0.40950716, 0.37321907, 0.43796128,
       0.35555974, 0.46106486, 0.35167441, 0.41176391, 0.46262618,
       0.48840862, 0.45380107, 0.45465366, 0.48307014, 0.49332007,
       0.41735341, 0.45948457, 0.45701078, 0.48064046, 0.49399533,
       0.48179554, 0.46827135, 0.48300636, 0.49490012, 0.47880855,
       0.47999003, 0.49268406, 0.49716116, 0.46274535, 0.49306379,
       0.48120165, 0.49347294, 0.49088899, 0.45399264, 0.48067857,
       0.49440125, 0.49007753, 0.47373256, 0.49273173, 0.48421988,
       0.49567049, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [225]:
# Pesos dos estimadores
boosting_model.estimator_weights_

array([0.34285567, 0.53183759, 0.25620218, 0.36290206, 0.17460816,
       0.41628218, 0.10923956, 0.42818108, 0.24967476, 0.10484225,
       0.03246168, 0.12972703, 0.12731959, 0.04742175, 0.01870492,
       0.23355321, 0.11369248, 0.12066773, 0.05423381, 0.01681389,
       0.05099503, 0.08895974, 0.04760052, 0.01428016, 0.05937162,
       0.05605785, 0.02048608, 0.00794883, 0.10450671, 0.01942263,
       0.05266021, 0.0182768 , 0.02551365, 0.12918601, 0.05412696,
       0.01567716, 0.02778655, 0.0736166 , 0.0203526 , 0.04419902,
       0.01212294, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [226]:
# Predizer a Probabilidade de Conversão
y_pred_prob = boosting_model.predict_proba(X_test)

In [227]:
# Visualizar Probabilidades
y_pred_prob

array([[0.2787737 , 0.7212263 ],
       [0.64592541, 0.35407459],
       [0.64592541, 0.35407459],
       ...,
       [0.69018394, 0.30981606],
       [0.75189773, 0.24810227],
       [0.2449924 , 0.7550076 ]], shape=(1815, 2))